### ISSUE TITLE
Implement cleanup_html

### ISSUE THREAD

**Issue by zac-garby** [Emersont1/dndb-scrapers#19]
A function to remove class names from HTML.

From: https://github.com/users/Emersont1/projects/1#card-35181369

Still not sure of the exact reason this needs to be done, couldn't the class-names just be ignored during scraping?

**Comment by Emersont1** [comment]
i can't find a way in beautifulsoup to delete classes, there may be a way, but i'm not 100%

**Comment by zac-garby** [comment]
why does it matter if there's a class which you don't care about?

**Comment by Emersont1** [comment]
Cleans up output, makes it smaller

**Comment by Emersont1** [comment]
with #24
